**Paragraph 2.1**
Calculation of pi vector throgh raising P matrix to power of 2, 32:

In [3]:
from numpy import *

P = array([ [0, 1/2.0, 1/3.0, 1, 0    ],
            [1, 0,     1/3.0, 0, 1/3.0],
            [0, 1/2.0, 0,     0, 1/3.0],
            [0, 0,     0,     0, 1/3.0],
            [0, 0,     1/3.0, 0, 0    ] ])

# P in power 2
dot(P, P)

array([[0.5       , 0.16666667, 0.16666667, 0.        , 0.61111111],
       [0.        , 0.66666667, 0.44444444, 1.        , 0.11111111],
       [0.5       , 0.        , 0.27777778, 0.        , 0.16666667],
       [0.        , 0.        , 0.11111111, 0.        , 0.        ],
       [0.        , 0.16666667, 0.        , 0.        , 0.11111111]])

In [4]:
# P in power 32
linalg.matrix_power(P, 32)

array([[0.2926887 , 0.29267874, 0.2926823 , 0.29267624, 0.29268625],
       [0.39023707, 0.39025042, 0.39024059, 0.39024865, 0.39024485],
       [0.2195134 , 0.21950912, 0.21951777, 0.21951526, 0.21950602],
       [0.02438908, 0.02439058, 0.02439168, 0.02439262, 0.024388  ],
       [0.07317175, 0.07317113, 0.07316766, 0.07316723, 0.07317488]])

**Paragraph 3.2**
Computing egenvectors using power method

In [8]:
# Basic power method without matrix transformations
def powerMethodBasic(A,x0,iter):
 """ basic power method """
 for i in range(iter):
  x0 = dot(A,x0)
  x0 = x0/linalg.norm(x0,1)
 return x0

# Basic parameters
n = P.shape[1]
x0 = [1]*n
powerMethodBasic(P, x0, 15)

array([0.29280598, 0.39024762, 0.21932759, 0.02431712, 0.07330169])

As we can see this basic power method converges already after 15 iterations.

In [9]:
def powerMethodAdvanced(A,x0,m,iter):
    """ power method changed to compute
        the maximal eigenvector
        of the matrix M built on top of the matrix P"""
    n = P.shape[1]
    delta = m*(array([1]*n,dtype='float64')/n) # array([1]*n is [1 1 ... 1] n times
    for i in range(iter):
        x0 = dot((1-m),dot(A,x0)) + delta
    return x0

m = 0.15
powerMethodAdvanced(P, x0, m, 100)

array([0.28856915, 0.35939074, 0.20793352, 0.05519244, 0.0889145 ])

As we can see modified power method produces slightly different results from basic one. But it handles corner cases as it's described in the report and the actual score order didn't change.